include_guard(GLOBAL)

if(NOT DEFINED ENV{VCPKG_ROOT})
    message(FATAL_ERROR "VCPKG_ROOT environment variable was not set.")
endif()

if (WIN32)
    set(VCPKG_PROGRAM "$ENV{VCPKG_ROOT}/vcpkg.exe")
else()
    set(VCPKG_PROGRAM "$ENV{VCPKG_ROOT}/vcpkg")
endif()

function(vcpkg_install PACKAGE PACKAGE_NAME WITH_CONFIG)
    message(STATUS "finding ${PACKAGE}")
    if (WITH_CONFIG)
        find_package(${PACKAGE} CONFIG)
    else()
        find_package(${PACKAGE})
    endif()
    
    if(NOT ${${PACKAGE}_FOUND})
        message(STATUS "installing ${PACKAGE} via vcpkg")
        execute_process(COMMAND ${VCPKG_PROGRAM} install ${PACKAGE_NAME} --triplet=${VCPKG_TARGET_TRIPLET})
        if (WITH_CONFIG)
            find_package(${PACKAGE} CONFIG REQUIRED)
        else()
            find_package(${PACKAGE} REQUIRED)
        endif()
    endif()
endfunction()

function(vcpkg_install_force PACKAGE_NAME_ARGS)
    foreach(ARG IN LISTS ARGV)
        message(STATUS "installing ${ARG} via vcpkg")
        execute_process(COMMAND ${VCPKG_PROGRAM} install ${ARG} --triplet=${VCPKG_TARGET_TRIPLET})
    endforeach()
endfunction()
