name: wasm32-unknown-emscripten

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"
  EMSDK: "${{ github.workspace }}/emsdk"
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Analyze
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk.bat install latest
          ./emsdk.bat activate latest
          ./emsdk_env.bat
          cd ..

      - name: Configure CMake in Debug mode
        run: cmake -S . -B ${{ env.build }} --preset=wasm32-unknown-emscripten -DWOLF_FEATURES_ALL=ON
 
      - name: Build CMake in Debug mode
        run: cmake --build ${{ env.build }} --config Debug

      - name: Build CMake in Release mode
        run: cmake --build ${{ env.build }} --config Release
          
